[project]
name = "poker"
version = "1.0.0"
description = "The playground for exciting poker plays!"
dependencies = [
    "flask", "requests"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"